# Generated by Django 6.0 on 2025-12-09 17:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeGrid',
            fields=[
                ('grid_id', models.IntegerField(help_text='Unique grid identifier', primary_key=True, serialize=False, unique=True)),
                ('center_longitude', models.FloatField()),
                ('center_latitude', models.FloatField()),
                ('southwest_lat', models.FloatField()),
                ('southwest_lng', models.FloatField()),
                ('northeast_lat', models.FloatField()),
                ('northeast_lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crime Grid',
                'verbose_name_plural': 'Crime Grids',
                'db_table': 'crime_grids',
                'ordering': ['grid_id'],
            },
        ),
        migrations.CreateModel(
            name='BaselinePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_period', models.IntegerField(help_text='YearMonth format: YYYYMM')),
                ('baseline_predicted_count', models.FloatField(help_text='Baseline predicted crime count')),
                ('rank', models.IntegerField(blank=True, help_text='Rank of the grid for this period', null=True)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_predictions', to='storing.crimegrid')),
            ],
            options={
                'verbose_name': 'Baseline Prediction',
                'verbose_name_plural': 'Baseline Predictions',
                'db_table': 'baseline_predicted',
                'unique_together': {('grid', 'target_period')},
            },
        ),
        migrations.CreateModel(
            name='ActualCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_period', models.IntegerField(help_text='YearMonth format: YYYYMM', validators=[django.core.validators.MinValueValidator(202001)])),
                ('actual_crime_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual Crime Count')),
                ('rank', models.IntegerField(blank=True, help_text='Rank of the grid for this period', null=True)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('grid', models.ForeignKey(help_text='Reference to the grid', on_delete=django.db.models.deletion.CASCADE, related_name='actual_crimes', to='storing.crimegrid')),
            ],
            options={
                'verbose_name': 'Actual Crime Record',
                'verbose_name_plural': 'Actual Crime Records',
                'db_table': 'actual_predicted',
                'ordering': ['target_period', '-actual_crime_count'],
                'unique_together': {('grid', 'target_period')},
            },
        ),
        migrations.CreateModel(
            name='MLPPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_period', models.IntegerField(help_text='YearMonth format: YYYYMM', validators=[django.core.validators.MinValueValidator(202001)])),
                ('mlp_crime_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual Crime Count')),
                ('rank', models.IntegerField(blank=True, help_text='Rank of the grid for this period', null=True)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('grid', models.ForeignKey(help_text='Reference to the grid', on_delete=django.db.models.deletion.CASCADE, related_name='mlp_predicted_crimes', to='storing.crimegrid')),
            ],
            options={
                'verbose_name': 'MLP Prediction',
                'verbose_name_plural': 'MLP Predictions',
                'db_table': 'mlp_predicted',
                'unique_together': {('grid', 'target_period')},
            },
        ),
    ]
