# Generated by Django 6.0 on 2025-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=255)),
                ('target_period', models.IntegerField(help_text='YearMonth format: YYYYMM')),
                ('pei_percent', models.FloatField(help_text='PEI')),
                ('accuracy', models.FloatField(help_text='Accuracy')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'db_table': 'metric',
                'unique_together': {('model', 'target_period')},
            },
        ),
    ]
