# Generated by Django 6.0 on 2025-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storing', '0002_metricdata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actualcrime',
            index=models.Index(fields=['target_period', 'rank'], name='actual_pred_target__992aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='baselineprediction',
            index=models.Index(fields=['target_period', 'rank'], name='baseline_pr_target__45509e_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpprediction',
            index=models.Index(fields=['target_period', 'rank'], name='mlp_predict_target__65df24_idx'),
        ),
    ]
